#!/bin/bash

PROJECT_DIR="$(cd $(dirname "${BASH_SOURCE[0]}"); pwd)"
TEST_DIR="${PROJECT_DIR}/tests"
BUILD_DIR="${PROJECT_DIR}/build"
HOME="${BUILD_DIR}/home"

mkdir -p "$HOME"

exec /usr/bin/env -i HOME="$HOME" LOGNAME=$LOGNAME USER=$USER \
    PATH=/usr/bin:/bin:/sbin \
    SHLVL=$(( $SHLVL-1 )) \
    TERM="$TERM" \
    TEST_DIR="$TEST_DIR" \
    PROJECT_DIR="$PROJECT_DIR" \
    BUILD_DIR="$BUILD_DIR" \
    CONDA_SUBDIR= \
    CONDARC= \
    "$SHELL"
