#!/usr/bin/env python3

"""
Top-level entry point into the infrastructure-as-code system. This will switch
from whatever implementation of Python 3 is running now to the version of Python
installed with the engine. Any command line arguments will be passed to another
script running on the engine's Python interpreter.

By using the Python interpreter bundled with the engine, we ensure that all
dependencies are satisfied.
"""

from engine import exec

exec()
